export const workflowStages = [
  "Signal",
  "Enrichment",
  "Qualification",
  "Human Review",
  "Outreach",
  "Discovery Call",
  "Paid Assessment",
  "Report",
  "Follow-On Opportunity",
  "Closed Won",
];

export const opportunityRecords = [
  {
    name: "Capital Ridge Senior Living",
    market: "Alexandria, VA",
    buildingType: "Senior living / healthcare-adjacent",
    signal: "Closeout + fire alarm permit activity",
    score: 92,
    confidence: "0.84",
    firstOffer: "Public safety radio testing",
    state: "Human Review",
    stakeholderPath: "General contractor PM -> fire alarm partner -> owner rep",
    nextAction: "Approve first-touch message",
    why: "Potential closeout risk where a bounded diagnostic test creates a clear first paid step.",
    conversion: "Test -> report -> roadmap -> design / monitoring",
  },
  {
    name: "HarborPoint Garage",
    market: "Bethesda, MD",
    buildingType: "Parking garage / mixed-use",
    signal: "Coverage complaints + below-grade structure",
    score: 88,
    confidence: "0.81",
    firstOffer: "Cellular / DAS benchmark",
    state: "Outreach Ready",
    stakeholderPath: "Property manager -> garage operator -> owner",
    nextAction: "Send approved benchmark note",
    why: "Below-grade garage and complaint language point toward a benchmark report as a low-friction diagnostic.",
    conversion: "Benchmark -> findings -> remediation roadmap -> design package",
  },
  {
    name: "Arlington Medical Pavilion",
    market: "Arlington, VA",
    buildingType: "Healthcare commercial",
    signal: "Existing system age + facilities signal",
    score: 85,
    confidence: "0.78",
    firstOffer: "System health check",
    state: "Enriching",
    stakeholderPath: "Facilities director -> property manager",
    nextAction: "Verify system vendor history",
    why: "Existing system risk creates a maintenance and monitoring wedge before a large project ask.",
    conversion: "Health check -> report -> maintenance / monitoring",
  },
  {
    name: "Mosaic West Hotel",
    market: "Washington, DC",
    buildingType: "Hotel / hospitality",
    signal: "Guest coverage complaints",
    score: 82,
    confidence: "0.72",
    firstOffer: "Coverage benchmark",
    state: "Follow-Up Due",
    stakeholderPath: "General manager -> ownership group",
    nextAction: "Day 3 follow-up",
    why: "Hospitality pain language is noisy but useful when paired with an objective benchmark offer.",
    conversion: "Benchmark -> findings -> maintenance / upgrade",
  },
  {
    name: "DC Mixed-Use Tower",
    market: "Washington, DC",
    buildingType: "Office / residential / retail",
    signal: "Ownership change + portfolio map",
    score: 79,
    confidence: "0.69",
    firstOffer: "Portfolio risk screen",
    state: "Nurture",
    stakeholderPath: "Asset manager -> property manager",
    nextAction: "Hold pending contact verification",
    why: "Ownership movement creates a portfolio-level risk review angle.",
    conversion: "Screen -> benchmark shortlist -> multi-site roadmap",
  },
];

export const surfaces = [
  {
    id: "command-center",
    nav: "Command Center",
    title: "Command Center",
    eyebrow: "Growth Operations / Primary Workspace",
    summary: "Mission-control dashboard for active queues, recent signals, top opportunities, and first paid step momentum.",
    selected: "Capital Ridge Senior Living",
    primaryAction: "Approve Next Best Action",
    metrics: [
      ["High Score Opportunities", "18", "+6 since last scan", "Score 80+ / human review", "danger", "target"],
      ["Paid Assessment Fit", "9", "Survey/test ready", "First offer match", "success", "dollar"],
      ["Approval Queue", "7", "3 first-touch drafts", "No auto-send", "warning", "check"],
      ["Follow-Ups Due", "11", "2 overdue", "Cadence enforcement", "purple", "refresh"],
      ["Source Confidence", "0.84", "weighted trust", "4 stale sources", "blue", "shield"],
      ["Qualified Conversations", "5", "2 booked / 3 pending", "First 30 days", "neutral", "users"],
    ],
    filters: ["Market: VA / MD / DC", "Signal Lane: All", "Score: 70+", "State: Active", "First Offer: Survey / Test / Review"],
    table: {
      count: "246 records",
      columns: ["Rank", "Opportunity", "Signal / Trigger", "Score", "Recommended First Offer", "Stakeholder Path", "State", "Next Action"],
      rows: opportunityRecords.map((record, index) => ({
        id: record.name,
        cells: [
          String(index + 1).padStart(2, "0"),
          `${record.name}|${record.market} / ${record.buildingType}`,
          record.signal,
          String(record.score),
          record.firstOffer,
          record.stakeholderPath,
          record.state,
          record.nextAction,
        ],
      })),
    },
    expanded: {
      title: "Capital Ridge Senior Living",
      description: "High-confidence opportunity where the first paid step is a low-friction test or inspection that gives the buyer a clear report and risk posture.",
      evidence: [
        ["Permit / inspection signal", "System / 0.87", "Fire alarm permit and closeout-like activity identified. Source links retained for operator review."],
        ["Building risk profile", "Derived / 0.82", "Large, hard-to-cover facility type with public-safety sensitivity and likely radio/cellular exposure."],
        ["Partner ecosystem", "Manual review / 0.76", "Project team and fire alarm contractor path appears stronger than direct owner cold outreach."],
      ],
      actions: [
        "Approve outreach angle around de-risking closeout and producing a clear report.",
        "Verify general contractor PM and fire alarm contacts before first message.",
        "Queue Day 0 intro, Day 3 value follow-up, and Day 7 referral path.",
      ],
      gates: ["Captured", "Enriched", "Scored", "Review", "Outreach", "Discovery", "Assessment"],
    },
  },
  {
    id: "signal-intake",
    nav: "Signal Intake",
    title: "Signal Intake and Source Registry",
    eyebrow: "Growth Operations / Source Control",
    summary: "Monitor source health, captured signals, data quality, routing rules, and enrichment readiness.",
    selected: "Arlington County Permit Portal",
    primaryAction: "Run Selected Source",
    metrics: [
      ["Sources Monitored", "64", "11 active lanes", "Permits, plans, reviews, partners", "neutral", "source"],
      ["Signals Captured", "248", "+37 this week", "41 routed to enrichment", "blue", "activity"],
      ["Stale Sources", "4", "Needs owner check", "Last refresh > 14 days", "warning", "clock"],
      ["Parser Exceptions", "6", "3 resolved today", "Queued for source fix", "danger", "alert"],
      ["Avg Source Trust", "0.82", "weighted by lane", "Permit portals strongest", "success", "shield"],
      ["New Closeout Signals", "18", "high urgency", "Next 45 days", "purple", "flag"],
    ],
    filters: ["Lane: All", "Freshness: Current", "Trust >= 0.70", "Exceptions: Open"],
    sourceCards: [
      ["Permit Portals", "High trust", "County and city permits, fire alarm permits, certificate-of-occupancy activity, and planning applications."],
      ["Construction Intelligence", "Medium trust", "General contractor project pages, plan rooms, bid boards, public project trackers, and development coverage."],
      ["Reviews + Complaints", "Pain signal", "Public review text and forums that indicate weak cellular coverage, dead zones, or below-grade issues."],
      ["Partner Ecosystem", "Warm path", "Fire alarm, low-voltage, contractor, property management, and facility-service relationship signals."],
    ],
    table: {
      count: "64 sources",
      columns: ["Source", "Lane", "Refresh", "Trust", "Signals", "Exceptions", "Routed To", "Next Run"],
      rows: [
        ["Arlington County Permit Portal|Commercial permits, fire alarm permits, certificate-of-occupancy signals", "Permit monitor", "6 hours", "87", "31 / week", "1 warning", "Research & enrichment", "14:00"],
        ["Fairfax County Development Projects|Planning board and development announcements", "Construction intel", "Daily", "79", "18 / week", "Clean", "Construction monitor", "06:00"],
        ["Google Reviews / Hospitality Coverage|Hotel and garage coverage complaints", "Complaint patterns", "Weekly", "68", "12 / week", "Needs sample", "Complaint pattern agent", "Monday"],
        ["DC Ownership Change Feed|Commercial property transfers and portfolio signals", "Ownership change", "Weekly", "74", "7 / week", "Clean", "Portfolio mapping", "Friday"],
      ].map((cells, index) => ({ id: cells[0].split("|")[0] || `source-${index}`, cells })),
    },
    expanded: {
      title: "Arlington County Permit Portal",
      description: "Extraction contract provides project name, address, permit type, applicant, contractor references, permit date, and inspection-stage hints.",
      evidence: [
        ["Fire alarm permit", "Route", "Route to public-safety radio testing scorer."],
        ["Commercial closeout", "Route", "Route to closeout signal agent."],
        ["Large building / garage", "Route", "Route to benchmark or inspection first-offer mapping."],
      ],
      actions: [
        "Verify one naming mismatch between permit applicant and property ownership before auto-enrichment.",
        "Accept source health after parser warning is classified.",
        "Retain source links on every routed candidate lead.",
      ],
      gates: ["Ingest", "Parse", "Normalize", "Deduplicate", "Route", "Enrich"],
    },
  },
  {
    id: "opportunity-workbench",
    nav: "Opportunity Workbench",
    title: "Opportunity Workbench",
    eyebrow: "Growth Operations / Qualification",
    summary: "Score, prioritize, assign, and manage opportunity state from signal to human-reviewed outreach.",
    selected: "HarborPoint Garage",
    primaryAction: "Promote to Review",
    metrics: [
      ["Candidate Leads", "246", "150-250 target", "Raw signals converted to records", "blue", "table"],
      ["Enriched Records", "112", "45% complete", "Owner/contact/source fields", "neutral", "database"],
      ["Score 80+", "18", "High priority", "Review this week", "danger", "target"],
      ["Needs Contact Verify", "29", "Offshore queue", "Role confidence gaps", "warning", "users"],
      ["First Offer Fit", "67", "Survey/test/review", "Clear diagnostic wedge", "success", "arrowUp"],
      ["Duplicate Risk", "3%", "Below threshold", "Address/domain matching", "neutral", "merge"],
    ],
    filters: ["State: Active", "Market: VA / MD / DC", "Offer Fit: High", "Confidence >= .65", "Owner: Unassigned"],
    table: {
      count: "246 opportunities",
      columns: ["Opportunity", "Building Type", "Signal Lane", "Score", "Confidence", "First Offer", "State", "Owner"],
      rows: opportunityRecords.map(record => ({
        id: record.name,
        cells: [`${record.name}|${record.market}`, record.buildingType, record.signal, String(record.score), record.confidence, record.firstOffer, record.state, "Adam / Research"],
      })),
    },
    expanded: {
      title: "HarborPoint Garage",
      description: "The practical hook is a benchmark report that validates user experience and below-grade coverage risk, not a full system pitch.",
      evidence: [
        ["Building Fit", "18/20", "Below-grade garage and mixed-use profile strongly match the diagnostic wedge."],
        ["Urgency", "14/20", "Complaint language is useful but needs current validation."],
        ["Paid Step Fit", "19/20", "$7K-$12K cellular/DAS benchmark is a bounded first paid step."],
      ],
      actions: [
        "Approve benchmark message around objective testing, documentation, and optional roadmap.",
        "Attach source notes internally only.",
        "Verify property manager/operator contact before outreach.",
      ],
      gates: workflowStages.slice(0, 7),
    },
  },
  {
    id: "evidence-review",
    nav: "Evidence Review",
    title: "Evidence Review",
    eyebrow: "Growth Operations / Human Review",
    summary: "Review source evidence, confidence, stakeholder path, technical boundaries, and approval checklist.",
    selected: "Fire alarm permit pattern",
    primaryAction: "Approve Outreach Draft",
    metrics: [
      ["Evidence Packets", "112", "88 complete", "Source links + notes", "blue", "file"],
      ["High Confidence", "73", ">= 0.75", "Ready for scoring", "success", "shield"],
      ["Needs Verification", "24", "Contact/source gaps", "Research queue", "warning", "search"],
      ["Technical Handoff", "4", "SME review", "Coverage claims/pricing", "purple", "flag"],
      ["Ready Reports", "6", "Meeting briefs", "For discovery calls", "neutral", "fileText"],
      ["Rejected Records", "9", "Bad fit / duplicate", "Prevent waste", "danger", "x"],
    ],
    filters: ["Confidence: >= .75", "Use: Internal only", "Stakeholder: Needs verify", "SME: Hold technical claims"],
    table: {
      count: "112 evidence packets",
      columns: ["Evidence", "Source Type", "Confidence", "Freshness", "Use in Outreach?", "Notes"],
      rows: [
        ["Fire alarm permit pattern|Permit monitor detected relevant activity", "System source", "87", "6 days", "Internal only", "Use as internal trigger; avoid over-specific references."],
        ["Facility type risk|Senior living / large hard-to-cover building profile", "Derived", "82", "Current", "Generic angle", "Use generic testing/report value proposition."],
        ["Partner route|General contractor + fire alarm contractor path", "Manual review", "76", "Needs verify", "No", "Verify contacts before outreach."],
      ].map((cells, index) => ({ id: cells[0].split("|")[0] || `evidence-${index}`, cells })),
    },
    expanded: {
      title: "Capital Ridge Senior Living",
      description: "Potential survey/testing opportunity tied to closeout and public-safety radio coverage risk. First offer is diagnostic and report-driven.",
      evidence: [
        ["What it supports", "Approved for scoring", "Closeout/compliance-timing hypothesis, public safety radio testing relevance, and project-team stakeholder route."],
        ["What it does not prove", "No public claim", "It does not prove system failure, buyer urgency, or a specific technical diagnosis."],
        ["Quality decision", "Human approval", "Use evidence to prioritize outreach, not as a claim in the outbound message."],
      ],
      actions: [
        "Pass source traceability because source links are retained and summarized.",
        "Hold technical claims. Offer testing; do not claim failure.",
        "Verify contractor roles before first touch.",
      ],
      gates: ["Signal", "Evidence", "Review", "Outreach", "Discovery", "Paid Assessment"],
    },
  },
  {
    id: "outreach-queue",
    nav: "Outreach Queue",
    title: "Outreach Queue",
    eyebrow: "Growth Operations / Human-Gated Outreach",
    summary: "Approve draft outreach, enforce cadences, triage responses, and prepare discovery handoffs.",
    selected: "HarborPoint Garage",
    primaryAction: "Approve Selected",
    metrics: [
      ["Drafts Waiting", "7", "3 first-touch", "Human approval required", "warning", "mail"],
      ["Approved Sends", "22", "This week", "Operator-controlled", "success", "check"],
      ["Replies to Triage", "5", "2 positive", "Meeting or referral intent", "blue", "inbox"],
      ["Follow-Ups Due", "11", "2 overdue", "Cadence queue", "purple", "refresh"],
      ["Meeting Briefs", "3", "Generated", "For discovery calls", "neutral", "fileText"],
      ["Opt-Out / Stop", "1", "Respect immediately", "Governance guardrail", "danger", "shield"],
    ],
    filters: ["Queue: Approval", "Channel: All", "Age: 0-7 days", "Priority: High"],
    table: {
      count: "43 outreach tasks",
      columns: ["Opportunity", "Channel", "Draft Type", "First Offer", "Risk", "State", "Due", "Owner"],
      rows: [
        ["HarborPoint Garage|Property manager / operator path", "Email + LinkedIn", "First touch", "Benchmark", "Low", "Approval", "Today", "Adam"],
        ["Capital Ridge Senior Living|General contractor PM path", "Email", "First touch", "Radio testing", "Medium", "Technical review", "Today", "Farzin review"],
        ["Mosaic West Hotel|General manager", "Email", "Follow-up", "Coverage benchmark", "Low", "Due", "Today", "Adam"],
        ["Arlington Medical Pavilion|Facilities director", "Phone prep", "Call script", "Health check", "Low", "Research needed", "Tomorrow", "Researcher"],
      ].map((cells, index) => ({ id: cells[0].split("|")[0] || `outreach-${index}`, cells })),
    },
    expanded: {
      title: "PM benchmark draft",
      description: "Suggested message posture: professional, diagnostic, low-pressure. It offers testing and a clear report without claiming the building has failed coverage.",
      evidence: [
        ["Source-safe", "Pass", "Does not cite private assumptions or unverified complaint details."],
        ["Technical-safe", "Pass", "Offers testing; does not diagnose remotely."],
        ["Buyer-safe", "Pass", "Clear first paid step, not a large project ask."],
      ],
      actions: [
        "Day 0: send property manager note after approval.",
        "Day 3: follow up with benchmark/report value.",
        "Day 7: ask for right facilities contact or referral path.",
      ],
      gates: ["Draft", "Approval", "Send", "Reply", "Discovery", "Brief"],
    },
  },
  {
    id: "agent-operations",
    nav: "Agent Operations",
    title: "Agent Operations",
    eyebrow: "Growth Operations / Automation Control",
    summary: "Manage agent runs, source monitors, exceptions, offshore task packets, and the MVP tech stack.",
    selected: "Permit Monitor Agent",
    primaryAction: "Run Selected",
    metrics: [
      ["Agent Runs Today", "12", "9 successful", "Scheduled monitors", "blue", "settings"],
      ["New Records", "37", "from 5 lanes", "Queued for enrichment", "success", "plus"],
      ["Exceptions", "6", "3 parser / 3 contact", "Needs operator triage", "warning", "alert"],
      ["Offshore Tasks", "42", "18 due today", "Research + CRM hygiene", "purple", "list"],
      ["Avg Run Cost", "$3.80", "estimated", "Lightweight MVP", "neutral", "dollar"],
      ["Human Reviews", "7", "Approval queue", "Outbound boundary", "danger", "user-check"],
    ],
    filters: ["Status: Active", "Owner: All", "Exceptions: Open", "Run window: 24h"],
    table: {
      count: "8 agent workflows",
      columns: ["Agent / Workflow", "Purpose", "Trigger", "Tools Touched", "Output", "Status", "Owner"],
      rows: [
        ["Permit Monitor Agent|County/city permit + closeout activity", "Find buildings likely to need survey/testing before closeout", "Every 6 hours", "Scraper/API -> extractor -> CRM", "18 signals / 6 enriched", "Healthy", "Growth Ops"],
        ["Complaint Pattern Agent|Reviews, forums, public pain language", "Detect cellular dead-zone patterns", "Weekly", "Search/API -> text classifier -> tracker", "12 signals / 4 high fit", "Needs sample", "Researcher"],
        ["Portfolio Mapping Agent|Owner/property manager portfolios", "Map multi-building expansion wedges", "Daily", "Company sites -> contact enrichment", "9 accounts / 27 buildings", "Healthy", "Growth Ops"],
        ["Outreach Draft Agent|Context-aware message generation", "Draft human-approved outreach", "On review promotion", "Template library -> LLM -> approval queue", "7 drafts", "Human gate", "Adam"],
      ].map((cells, index) => ({ id: cells[0].split("|")[0] || `agent-${index}`, cells })),
    },
    expanded: {
      title: "Permit Monitor Agent",
      description: "Agent fleet, scheduled jobs, run logs, exceptions, and offshore task packets in one operating control surface.",
      evidence: [
        ["Agent", "Finds/extracts/scores/drafts", "Trigger, ingestion collectors, parser, normalizer, deduplication, enrichment, scoring, and first-offer recommendation."],
        ["Offshore", "Verifies contacts", "Checks roles, fills missing fields, updates tracker, and attaches source links."],
        ["Adam / Farzin", "Approves", "Outbound, technical claims, pricing, discovery, close strategy, and customer-facing commitments."],
      ],
      actions: [
        "Hold when source confidence is below .65.",
        "Hold when duplicate risk is above 10%.",
        "Hold when technical language is generated or a contact role is not verified.",
      ],
      gates: ["Trigger", "Collect", "Parse", "Normalize", "Score", "Draft", "Human Gate"],
    },
  },
  {
    id: "conversion-board",
    nav: "Conversion Board",
    title: "Conversion Board",
    eyebrow: "Growth Operations / Learning Loop",
    summary: "Track the path from market signal to first paid step, report delivery, and follow-on opportunities.",
    selected: "Capital Ridge Senior Living",
    primaryAction: "Log Outcome",
    metrics: [
      ["Qualified Conversations", "5", "2 booked calls", "First 30 days", "blue", "users"],
      ["Paid Assessment Candidates", "4", "$2.5K-$15K", "Survey/test/report wedge", "success", "dollar"],
      ["Reports Delivered", "1", "pilot target", "Creates conversion leverage", "neutral", "fileText"],
      ["Follow-On Opportunities", "3", "roadmap/design", "Path to larger work", "purple", "arrowUp"],
      ["Pipeline Value", "$42K", "assessment + design", "Early-stage estimate", "warning", "chart"],
      ["Closed-Won Work", "0", "trial phase", "Track after payment", "neutral", "check"],
    ],
    filters: ["First Offer: All", "Segment: All", "Source Lane: All", "Outcome: Active"],
    table: {
      count: "Conversion records",
      columns: ["Opportunity", "Signal", "First Paid Step", "Conversation", "Assessment", "Report", "Follow-On", "Learning"],
      rows: opportunityRecords.slice(0, 4).map(record => ({
        id: record.name,
        cells: [`${record.name}|${record.market}`, record.signal, record.firstOffer, record.state, record.score >= 85 ? "Candidate" : "Nurture", "-", record.conversion.split(" -> ").slice(-1)[0], record.why],
      })),
    },
    expanded: {
      title: "Signal -> Paid Diagnostic -> Larger Work",
      description: "The system is optimized for buyers who have a reason to buy clarity now, not for speculative full-project asks.",
      evidence: [
        ["Why this converts", "Diagnostic report", "It creates trust, identifies the problem, documents risk, and frames next-step options."],
        ["Why this is lower friction", "Bounded yes", "Buyer can approve a test, inspection, or benchmark before committing to design/build."],
        ["What to measure", "Conversion metrics", "Meeting-to-assessment and assessment-to-roadmap/design conversion."],
      ],
      actions: [
        "Promote learning that closeout and fire/life-safety-adjacent triggers should outrank generic outreach.",
        "Tune scoring based on first-offer performance.",
        "Prioritize portfolio risk screen and fire alarm contractor referral kit experiments.",
      ],
      gates: workflowStages,
    },
  },
];

export const sidebarKpis = [
  ["30d", "trial window"],
  ["1-3", "paid steps"],
];
